### ISSUE TITLE
Testing your lib using your stegotest CLI, and it appears to not be able to decode...

### ISSUE THREAD

**Issue by pblanton** [PapyrusCompendium/Steganography-Library#2]
In "DecodeImage()" you read the first four bytes to get the ended data length, but it is coming back zero. It appears that you never set the length of the encoded data into the first four bytes of the byte array before encoding it into the image.

![image](https://user-images.githubusercontent.com/1143649/100163099-2f523c00-2e72-11eb-9c32-393b4974117b.png)

**Comment by pblanton** [comment]
After more careful debugging, it appears that nothing is being embedded into the image. I'm not sure why, but there seems to be an error in the EncodeImageLSB() method that is preventing it from returning an encoded bitmap.

**Comment by PapyrusCompendium** [comment]
Thanks, I'll actually come back to this and re-write it with better practices. Learned a lot since I wrote this lib :)

**Comment by PapyrusCompendium** [comment]
I have completely re written this and is now unit tested. :)
